<a href="https://colab.research.google.com/github/Vixuz144/Simulaci-n-2/blob/main/Pruebas_algoritmo_evolutivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from random import random, randint

In [ ]:
def cruza_pareja(l1, l2, prob = [1/3, 2/3]):
  l1, l2 = np.array(l1), np.array(l2)
  n = len(l1)

  nl = []
  for p in prob:
    nl.append(p*l1 + (1-p)*l2)
  return np.array(nl)

Lo que diferencia a cada version de "cruza_poblacion" es el como empareja a la población para su recombinación

In [ ]:
def cruza_poblacion_v1(poblacion, prob = [1/3, 2/3]):
  p = np.array(poblacion)
  n = len(p[0,:])
  r = np.random.random((2,n))
  par = np.argsort(r,axis = 1)
  padres = p[:,par[0,:]]
  madres = p[:,par[1,:]]
  for p in prob:
    try:
      hijos = np.append(hijos, p*madres + (1-p)*padres, axis = 1)
    except:
      hijos = p*madres + (1-p)*padres
  return hijos

In [ ]:
def cruza_poblacion_v2(poblacion, prob = [1/3, 2/3]):
  p = np.array(poblacion)
  n = len(p[0,:])
  r = np.random.random(n)
  r1 = np.argsort(r)
  r2 = []
  for i in r1:
    r = np.pi
    while r != i:
      r = randint(0,n-1)
    r2.append(r)
  r2 = np.array(r2)
  padres = p[:,r1]
  madres = p[:,r2]

  for p in prob:
    try:
      hijos = np.hstack((hijos, p*madres + (1-p)*padres))
    except:
      hijos = p*madres + (1-p)*padres
  return hijos

In [ ]:
def cruza_poblacion_v3(poblacion, prob = [1/3, 2/3]):
  p = np.array(poblacion)
  n = len(p[0,:])
  r = np.random.random(n)
  r1 = np.argsort(r)
  r2 = r1[-1:n:1]
  padres = p[:,r1]
  madres = p[:,r2]

  for p in prob:
    try:
      hijos = np.append(hijos, p*madres + (1-p)*padres, axis = 1)
    except:
      hijos = p*madres + (1-p)*padres
  return hijos

Hay muchas maneras de mutar a un individuo. Dos de las que se  me ocurrieron son las siguientes:

In [ ]:
def mutacion_suma(l = np.array([1/4, 1/4, 1/4, 1/4]), intensidad = 0.1):
  n = len(l)
  r = randint(0,n-1)
  for i in range(n):
    if i == r:
      nl = l - intensidad
      nl[i] += intensidad*n
  return nl

In [ ]:
def mutacion_promedio(l = np.array([1/4, 1/4, 1/4, 1/4]), pond = 1/2):
  l = np.array(l)
  n = len(l)
  p = np.random.random(n)
  l = l[list(np.argsort(p))]
  nl = []
  for i in range(n):
    nl.append(l[i]*pond + l[i-1]*(1-pond))
  return np.array(nl)

Pruebas

In [ ]:
l = np.array([0.1, 0.2, 0.3, 0.4])
a = np.array([0.3, 0.3, 0.3, 0.1])

nl = cruza_pareja(a,l, [0.1, 0.9, 0.5])
print(nl)

k = 1
nl[k] = mutacion_suma(nl[k],10)
print(nl)

j = 0
nl[j] = mutacion_promedio(nl[j],0.5)
print(nl)

[[0.12 0.21 0.3  0.37]
 [0.28 0.29 0.3  0.13]
 [0.2  0.25 0.3  0.25]]
[[ 0.12  0.21  0.3   0.37]
 [-9.72 -9.71 30.3  -9.87]
 [ 0.2   0.25  0.3   0.25]]
[[ 0.165  0.29   0.335  0.21 ]
 [-9.72  -9.71  30.3   -9.87 ]
 [ 0.2    0.25   0.3    0.25 ]]


In [ ]:
def seleccion(lista_participantes, n_ganadores, f_evaluacion, min = False):
  l = np.array(lista_participantes)
  puntuacion = f_evaluacion(l)
  if min:
    ind = np.argsort(puntuacion)[:n_ganadores]
  else:
    ind = np.argsort(-puntuacion)[:n_ganadores]

  #print(ind)
  ganadores = l[:,ind]
  puntuacion = puntuacion[ind]
  return ganadores, puntuacion

***EL CODIGO***

In [ ]:
# población inicia, tamaño de selección, funcion, probabilidad de mutación, número de generaciones
def alg_evol(p0, tam, func, pm, no_gen):
  mej_gen = []
  punt = []
  p, s = seleccion(p0, tam, func, min = True)
  for i in range(no_gen):
    p, s = seleccion(p, tam, func, min = True)
    mej_gen.append(p[:,0].tolist())
    punt.append(s[0])

    p_nva = cruza_poblacion_v1(p, np.arange(0.1,0.9, 0.5))
    n = len(p_nva[0,:])
    # print(n)
    for i in range(n):
      r = random()
      if r < pm:
        p_nva[:,i] = mutacion_suma(p_nva[:,i], 0.1)
    p = p_nva

  return mej_gen, punt

Función:
$$ f(x_1, x_2, x_3, ..., x_n) = x_1^2 + x_2^2 + x_3^2 + ... + x_n^2 $$

In [ ]:
def f_prueba(x):
  a = np.array(x)
  return sum(a**2)

In [ ]:
a = np.array([[1,2],[3,4]])
print(f_prueba(a))
b = np.append(a,a,1)
print(np.append(b,a,1))

[10 20]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [ ]:
n = 10000                                             #Tamaño de la población
p0 = 2 * np.random.random((8,n)) - 1                  #Se genera una población aleatoria
#print(p0)
sol, feval = alg_evol(p0, 1000, f_prueba, 0.001, 100)
# print(sol, '\n')

print(feval[0])     #El puntaje del mejor individuo de la primera generación
print(feval[-1])    #El puntaje del mejor individuo de la última generación
print(min(feval))   #El puntaje del mejor individuo de todas las generaciones

0.30775820698854023
1.0261711826793093e-08
8.95003836109415e-09
